---
dev_addr: "127.0.0.1:8001"
<<<<<<< HEAD
edit_uri: "edit/develop/docs"
=======
edit_uri: "edit/main/pyntc/docs"
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
site_dir: "pyntc/static/pyntc/docs"
site_name: "Pyntc Documentation"
site_url: "https://pyntc.readthedocs.io/en/latest/"
repo_url: "https://github.com/networktocode/pyntc"
copyright: "Copyright &copy; The Authors"
theme:
  name: "material"
  navigation_depth: 4
  custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "python"
    - "yaml"
  features:
<<<<<<< HEAD
    - "content.code.annotate"
    - "content.code.copy"
    - "content.tabs.link"
    - "navigation.footer"
=======
    - "content.action.edit"
    - "content.action.view"
    - "content.code.copy"
    - "navigation.footer"
    - "navigation.indexes"
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
  favicon: "assets/favicon.ico"
  logo: "assets/networktocode_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
<<<<<<< HEAD

validation:
  absolute_links: "warn"
  anchors: "warn"
  omitted_files: "warn"
  unrecognized_links: "warn"

=======
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
extra_css:
  - "assets/extra.css"

extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/"
      name: "Network to Code Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCwBh-dDdoqzxXKyvTw3BuTw"
      name: "Network to Code Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "Network to Code Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/networktocode/"
      name: "GitHub Organization"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "Network to Code Twitter"
markdown_extensions:
  - "markdown_version_annotations":
      admonition_tag: "???"
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
<<<<<<< HEAD
  - "markdown_data_tables":
      base_path: "docs"
  - "md_in_html"
=======
  - "md_in_html"
  - "markdown_data_tables":
      base_path: "docs"
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
  - "pymdownx.details"
  # Need pymdownx.emoji for Grid icon search
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences":
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "pymdownx.tabbed":
      "alternate_style": true
  - "pymdownx.tilde"

plugins:
  - "search"
  - "gen-files":
      scripts:
        - "docs/generate_code_reference_pages.py"
  - "glightbox":
<<<<<<< HEAD
      manual: true # See https://blueswen.github.io/mkdocs-glightbox/flexibility/enable-by-image-or-page/
=======
      manual: true  # See https://blueswen.github.io/mkdocs-glightbox/flexibility/enable-by-image-or-page/
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
  - "section-index"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            heading_level: 1
            show_root_heading: true
            show_root_members_full_path: true
            show_source: false

<<<<<<< HEAD
=======
validation:
  absolute_links: "warn"
  anchors: "warn"
  omitted_files: "warn"
  unrecognized_links: "warn"

>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
nav:
  - Overview: "index.md"
  - User Guide:
      - Library Overview: "user/lib_overview.md"
      - Getting Started: "user/lib_getting_started.md"
<<<<<<< HEAD
=======
      - Using the Library: "user/lib_use_cases.md"
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
      - Frequently Asked Questions: "user/faq.md"
  - Administrator Guide:
      - Install and Configure: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Release Notes:
          - "admin/release_notes/index.md"
<<<<<<< HEAD
          - v0.0: "admin/release_notes/version_0.0.md"
          - v0.14: "admin/release_notes/version_0.14.md"
          - v0.15: "admin/release_notes/version_0.15.md"
          - v0.16: "admin/release_notes/version_0.16.md"
          - v0.17: "admin/release_notes/version_0.17.md"
          - v0.18: "admin/release_notes/version_0.18.md"
          - v0.19: "admin/release_notes/version_0.19.md"
          - v0.20: "admin/release_notes/version_0.20.md"
          - v1.0: "admin/release_notes/version_1.0.md"
          - v2.0: "admin/release_notes/version_2.0.md"
=======
          - v1.0: "admin/release_notes/version_1.0.md"
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
  - Developer Guide:
      - Extending the Library: "dev/extending.md"
      - Contributing to the Library: "dev/contributing.md"
      - Development Environment: "dev/dev_environment.md"
<<<<<<< HEAD
      - Code Reference:
          - pyntc: "code-reference/pyntc/__init__.md"
          - pyntc.errors: "code-reference/pyntc/errors.md"
          - pyntc.log: "code-reference/pyntc/log.md"
          - pyntc.devices: "code-reference/pyntc/devices/__init__.md"
          - pyntc.devices.aireos_device: "code-reference/pyntc/devices/aireos_device.md"
          - pyntc.devices.asa_device: "code-reference/pyntc/devices/asa_device.md"
          - pyntc.devices.base_device: "code-reference/pyntc/devices/base_device.md"
          - pyntc.devices.eos_device: "code-reference/pyntc/devices/eos_device.md"
          - pyntc.devices.f5_device: "code-reference/pyntc/devices/f5_device.md"
          - pyntc.devices.ios_device: "code-reference/pyntc/devices/ios_device.md"
          - pyntc.devices.iosxewlc_device: "code-reference/pyntc/devices/iosxewlc_device.md"
          - pyntc.devices.jnpr_device: "code-reference/pyntc/devices/jnpr_device.md"
          - pyntc.devices.nxos_device: "code-reference/pyntc/devices/nxos_device.md"
          - pyntc.devices.system_features: "code-reference/pyntc/devices/system_features/__init__.md"
          - pyntc.devices.system_features.base_feature: "code-reference/pyntc/devices/system_features/base_feature.md"
          - pyntc.devices.system_features.vlans: "code-reference/pyntc/devices/system_features/vlans/__init__.md"
          - pyntc.devices.system_features.vlans.base_vlans: "code-reference/pyntc/devices/system_features/vlans/base_vlans.md"
          - pyntc.devices.system_features.vlans.eos_vlans: "code-reference/pyntc/devices/system_features/vlans/eos_vlans.md"
          - pyntc.devices.tables: "code-reference/pyntc/devices/tables/__init__.md"
          - pyntc.devices.juniper: "code-reference/pyntc/devices/tables/jnpr/__init__.md"
          - pyntc.devices.juniper.loopback: "code-reference/pyntc/devices/tables/jnpr/loopback.md"
          - pyntc.utils: "code-reference/pyntc/utils/__init__.md"
          - pyntc.utils.converters: "code-reference/pyntc/utils/converters.md"
          - pyntc.utils.templates: "code-reference/pyntc/utils/templates/__init__.md"
          - pyntc.arch_decision: "dev/arch_decision.md"
=======
      - Release Checklist: "dev/release_checklist.md"
      - Architecture Design Records: "dev/arch_decision.md"
>>>>>>> 2122990 (Cookie initially baked targeting develop by NetworkToCode Cookie Drift Manager Tool)
